In [1]:
import pandas as pd

In [15]:
## series

In [9]:
data = [10, 20, 30, 40]
s = pd.Series(data)

In [10]:
s

0    10
1    20
2    30
3    40
dtype: int64

In [12]:
# data frame 

data={"name : abbas ","name : awais","name : murtaza","age :10 ","age :23 ","age :20 "
}

df=pd.DataFrame(data)
df

                0
0        age :10
1    name : awais
2        age :20
3   name : abbas
4  name : murtaza
5        age :23

In [14]:
import pandas as pd

data = [
    {"Name": "shoiab", "Age": 25, "Role": "Dev"},
    {"Name": "arslan", "Age": 30, "Role": "Designer"},
    {"Name": "abbas ", "Age": 35, "Role": "Manager"}
]

df2 = pd.DataFrame(data)

df2

     Name  Age      Role
0  shoiab   25       Dev
1  arslan   30  Designer
2  abbas    35   Manager